// Product_details_right.js

export const productDetails_right = {
    1: [
      { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
      { label: "Size", value: "10-15inch, 15-20inch" },
      { label: "Type", value: "Sprockets" },
      { label: "Material", value: "Alloy Steel" },
      { label: "Thickness", value: "5–15 mm" },
      { label: "Application", value: "Industrial Use" },
      { label: "Color", value: "Silver" },
      { label: "Availability", value: "Worldwide" },
    ],
    2: [
      { label: "Business Type", value: "Manufacturer, Exporter, Supplier" },
      { label: "Motor Power", value: "5-5-7hp,100 watt to100kw" },
      { label: "Driven Type", value: "Hydraulic, Electric, Diesel Engine" },
      { label: "Material", value: "Alloy Steel " },
      { label: "Style", value: "Vertical, Horizontal & Angular" },
      { label: "Application", value: "Industrial Use " },
      { label: "Finishing", value: "Polished" },
      { label: "Availability", value: "Worldwide" },
    ],
    3: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "Shape", value: "Round" },
        { label: "Type", value: " Drives" },
        { label: "Material", value: "Metal " },
        { label: "Finishing", value: "Polished" },
        { label: "Application", value: "Industrial Use " },
        { label: "Feature", value: "Durable" },
        { label: "Availability", value: "Worldwide" },
      ],
      4: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "Motor Power", value: "1-3hp" },
        { label: "Type", value: "Gearbox" },
        { label: "Material", value: "Aluminum " },
        { label: "Finishing", value: "Polished" },
        { label: "Application", value: "Automobiles, Industrial Use " },
        { label: "Input Speed", value: "1400rpm" },
        { label: "Availability", value: "Worldwide" },
      ],
      5: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "shape", value: "Round" },
        { label: "Size", value: " 8 inch, 10 inch, 14 inch" },
        { label: "Material", value: "Aluminum" },
        { label: "Finishing", value: "Polished" },
        { label: "Type", value: "Drive" },
        { label: "Application", value: "Automobiles, Industrial Use" },
        { label: "Availability", value: "Worldwide" },
      ],
      6: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "Type", value: "Pumps" },
        { label: "Weight", value: "10–20 kg" },
        { label: "Pressure", value: "High, Medium & Low Pressure" },
        { label: "Application", value: "Agriculture, Automotive, Industrial, Marine, Power" },
        { label: "Availability", value: "Worldwide" },
        { label: "Warranty", value: " 1 Year" },

      ],
      7: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "Type", value: "5-5-7hp,100 watt to100kw" },
        { label: "Driven Type", value: "Gears" },
        { label: "Material", value: "Mild Steel " },
        { label: "Color", value: " Metallic" },
        { label: "Weight", value: " 10–20 kg" },
        { label: "Application", value: "Automobiles, Industrial Use " },
        { label: "Finishing", value: "Polished" },
        { label: "Availability", value: "Worldwide" },
      ],
      8: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "Type", value: "Timing Pulleys" },
        { label: "Material", value: "Mild Steel" },
        { label: "Size", value: "60–75 Inch, 75–90 Inch, 90–105 Inch" },
        { label: "Material", value: " Aluminium" },
        { label: "Application", value: " Pulling " },
        { label: "Shape", value: " Round " },
        { label: "Thickness", value: " 10–15 mm, 15–20 mm " },
        { label: "Availability", value: "Worldwide" },
      ],
      9: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "Type", value: " Drives" },
        { label: "Phase", value: "Single Phase, Double Phase" },
        { label: "Power Source", value: "Electric" },
        { label: "Frequency", value: "50/60 Hz" },
        { label: "Application", value: "Inverters Use" },
        { label: "Availability", value: "Worldwide" },
      ],
      10: [
        { label: "Business Type", value: "Manufacturer, Exporter, Supplier, Retailer" },
        { label: "Type", value: " Drives" },
        { label: "Weight", value: "100–1000 kg" },
        { label: "Rope Thickness", value: "10–15 mm, 15–20 mm" },
        { label: "Color", value: " Available in Many Colors" },
        { label: "Application", value: "Industrial" },
        { label: "Availability", value: "Worldwide" },
      ],
    // Add more entries here for other product IDs...
  };
  